### ISSUE TITLE
server side rendering

### ISSUE THREAD

**Issue by cescoferraro** [tiberiuc/redux-react-firebase#58]
when trying to call createStoreWithFirebase on the server I get this error.

```
export const createStoreWithFirebase = compose(
    reduxReactFirebase(config),
)(createStore);
```
  I can recreate the error if I import firebase from the server

```
import * as firebase from "firebase"
console.log(firebase);
```

```
ReferenceError: self is not defined
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:25:367)
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:37:614)
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:38:4)
    at Object../node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1)
    at __webpack_require__ (/srv/eat/www/server.bundle.js:21:30)
    at eval (eval at ./node_modules/firebase/firebase-browser.js (/srv/eat/www/server.bundle.js:1160:1), <anonymous>:12:1)
    at Object../node_modules/firebase/firebase-browser.js (/srv/eat/www/server.bundle.js:1160:1)
    at __webpack_require__ (/srv/eat/www/server.bundle.js:21:30)
    at eval (eval at ./node_modules/redux-react-firebase/build/compose.js (/srv/eat/www/server.bundle.js:4962:1), <anonymous>:7:17)
    at Object../node_modules/redux-react-firebase/build/compose.js (/srv/eat/www/server.bundle.js:4962:1)
ReferenceError: self is not defined
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:25:367)
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:37:614)
    at eval (eval at ./node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1), <anonymous>:38:4)
    at Object../node_modules/firebase/messaging.js (/srv/eat/www/server.bundle.js:1167:1)
    at __webpack_require__ (/srv/eat/www/server.bundle.js:21:30)
    at eval (eval at ./node_modules/firebase/firebase-browser.js (/srv/eat/www/server.bundle.js:1160:1), <anonymous>:12:1)
    at Object../node_modules/firebase/firebase-browser.js (/srv/eat/www/server.bundle.js:1160:1)
    at __webpack_require__ (/srv/eat/www/server.bundle.js:21:30)
    at eval (eval at ./node_modules/redux-react-firebase/build/compose.js (/srv/eat/www/server.bundle.js:4962:1), <anonymous>:7:17)
    at Object../node_modules/redux-react-firebase/build/compose.js (/srv/eat/www/server.bundle.js:4962:1)

```
`    at eval (eval at ./node_modules/redux-react-firebase/build/compose.js(/srv/eat/www/server.bundle.js:4962:1), <anonymous>:7:17)`
line 7 on compose.js requires firebase and it errors when ran on the server

**Comment by cescoferraro** [comment]
I get similar error when using re-base. If I `import * as Rebase from "re-base"` instead of `var Rebase = require("re-base")`
It somewhy import firebase-browser.js
